### PR TITLE
Update codeowners

### PR DESCRIPTION
**Pull request by epapbak**
# Description

Update code owners

### CODE REVIEW

**Comment by Bee-lee** [comment]
LGTM but this is just for the list of people who'll get notified about a new PR, no?

**Review by Bee-lee — APPROVED** [review]

**Comment by epapbak** [comment]
> LGTM but this is just for the list of people who'll get notified about a new PR, no?

yep, and I just updated it to see if I can merge commits.

**Comment by Bee-lee** [comment]
don't think so. thats up to project member permissions.

**Review by tisnik — APPROVED** [review]
LGTM

**Pull request merged**
